// API Endpoints
export const API_ENDPOINTS = {
  PORTFOLIOS: '/portfolios/',
  PORTFOLIO_DETAIL: (slug: string) => `/portfolios/${slug}/`,
  BLOGS: '/blogs/',
  BLOG_DETAIL: (slug: string) => `/blogs/${slug}/`,
  CERTIFICATES: '/certificates/',
  CERTIFICATE_DETAIL: (id: number) => `/certificates/${id}/`,
  AWARDS: '/awards/',
  AWARD_DETAIL: (id: number) => `/awards/${id}/`,
  JOBS: '/jobs/',
  JOB_DETAIL: (id: number) => `/jobs/${id}/`,
  DASHBOARD: '/dashboard/',
  CONTACT: '/contact/',
  CHATBOT: '/chatbot/chat/',
} as const;

// Redux Action Types
export const PORTFOLIO_ACTIONS = {
  FETCH_PORTFOLIOS_REQUEST: 'FETCH_PORTFOLIOS_REQUEST',
  FETCH_PORTFOLIOS_SUCCESS: 'FETCH_PORTFOLIOS_SUCCESS',
  FETCH_PORTFOLIOS_ERROR: 'FETCH_PORTFOLIOS_ERROR',
  FETCH_PORTFOLIO_DETAIL_REQUEST: 'FETCH_PORTFOLIO_DETAIL_REQUEST',
  FETCH_PORTFOLIO_DETAIL_SUCCESS: 'FETCH_PORTFOLIO_DETAIL_SUCCESS',
  FETCH_PORTFOLIO_DETAIL_ERROR: 'FETCH_PORTFOLIO_DETAIL_ERROR',
} as const;

export const BLOG_ACTIONS = {
  FETCH_BLOGS_REQUEST: 'FETCH_BLOGS_REQUEST',
  FETCH_BLOGS_SUCCESS: 'FETCH_BLOGS_SUCCESS',
  FETCH_BLOGS_ERROR: 'FETCH_BLOGS_ERROR',
  FETCH_BLOG_DETAIL_REQUEST: 'FETCH_BLOG_DETAIL_REQUEST',
  FETCH_BLOG_DETAIL_SUCCESS: 'FETCH_BLOG_DETAIL_SUCCESS',
  FETCH_BLOG_DETAIL_ERROR: 'FETCH_BLOG_DETAIL_ERROR',
} as const;

export const CERTIFICATE_ACTIONS = {
  FETCH_CERTIFICATES_REQUEST: 'FETCH_CERTIFICATES_REQUEST',
  FETCH_CERTIFICATES_SUCCESS: 'FETCH_CERTIFICATES_SUCCESS',
  FETCH_CERTIFICATES_ERROR: 'FETCH_CERTIFICATES_ERROR',
  FETCH_CERTIFICATE_DETAIL_REQUEST: 'FETCH_CERTIFICATE_DETAIL_REQUEST',
  FETCH_CERTIFICATE_DETAIL_SUCCESS: 'FETCH_CERTIFICATE_DETAIL_SUCCESS',
  FETCH_CERTIFICATE_DETAIL_ERROR: 'FETCH_CERTIFICATE_DETAIL_ERROR',
} as const;

export const AWARD_ACTIONS = {
  FETCH_AWARDS_REQUEST: 'FETCH_AWARDS_REQUEST',
  FETCH_AWARDS_SUCCESS: 'FETCH_AWARDS_SUCCESS',
  FETCH_AWARDS_ERROR: 'FETCH_AWARDS_ERROR',
  FETCH_AWARD_DETAIL_REQUEST: 'FETCH_AWARD_DETAIL_REQUEST',
  FETCH_AWARD_DETAIL_SUCCESS: 'FETCH_AWARD_DETAIL_SUCCESS',
  FETCH_AWARD_DETAIL_ERROR: 'FETCH_AWARD_DETAIL_ERROR',
} as const;

export const JOB_ACTIONS = {
  FETCH_JOBS_REQUEST: 'FETCH_JOBS_REQUEST',
  FETCH_JOBS_SUCCESS: 'FETCH_JOBS_SUCCESS',
  FETCH_JOBS_ERROR: 'FETCH_JOBS_ERROR',
  FETCH_JOB_DETAIL_REQUEST: 'FETCH_JOB_DETAIL_REQUEST',
  FETCH_JOB_DETAIL_SUCCESS: 'FETCH_JOB_DETAIL_SUCCESS',
  FETCH_JOB_DETAIL_ERROR: 'FETCH_JOB_DETAIL_ERROR',
} as const;

export const DASHBOARD_ACTIONS = {
  FETCH_DASHBOARD_REQUEST: 'FETCH_DASHBOARD_REQUEST',
  FETCH_DASHBOARD_SUCCESS: 'FETCH_DASHBOARD_SUCCESS',
  FETCH_DASHBOARD_ERROR: 'FETCH_DASHBOARD_ERROR',
} as const;

export const CHATBOT_ACTIONS = {
  SEND_MESSAGE_REQUEST: 'SEND_MESSAGE_REQUEST',
  SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
  SEND_MESSAGE_ERROR: 'SEND_MESSAGE_ERROR',
  CLEAR_MESSAGES: 'CLEAR_MESSAGES',
  SET_SESSION: 'SET_SESSION',
  LOAD_SESSION: 'LOAD_SESSION',
  ADD_USER_MESSAGE: 'ADD_USER_MESSAGE',
  ADD_ASSISTANT_MESSAGE: 'ADD_ASSISTANT_MESSAGE',
} as const;

export const CONTACT_ACTIONS = {
  SUBMIT_CONTACT_REQUEST: 'SUBMIT_CONTACT_REQUEST',
  SUBMIT_CONTACT_SUCCESS: 'SUBMIT_CONTACT_SUCCESS',
  SUBMIT_CONTACT_ERROR: 'SUBMIT_CONTACT_ERROR',
  RESET_CONTACT_STATE: 'RESET_CONTACT_STATE',
} as const;
